"""PDF payslip generation service."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import os

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.payroll import PayrollItem, Payslip
from app.services.errors import NotFoundError, ServiceError


PAYSLIP_STORAGE_DIR = Path(os.getenv("PAYSLIP_STORAGE_DIR", "storage/payslips"))


async def generate_payslip(payroll_item_id: int, db: AsyncSession) -> dict:
    """Generate or replace a PDF payslip for a payroll item."""
    item = await db.scalar(
        select(PayrollItem)
        .options(
            selectinload(PayrollItem.employee),
            selectinload(PayrollItem.payroll_run),
        )
        .where(PayrollItem.id == payroll_item_id)
    )
    if item is None:
        raise NotFoundError("Payroll item not found")
    if item.employee is None or item.payroll_run is None:
        raise ServiceError("Payroll item is missing employee or run data", status_code=500)

    PAYSLIP_STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    pdf_path = PAYSLIP_STORAGE_DIR / (
        f"payslip-{item.payroll_run.year}-{item.payroll_run.month:02d}-"
        f"{item.employee_id}.pdf"
    )
    _write_payslip_pdf(item, pdf_path)

    payslip = await db.scalar(select(Payslip).where(Payslip.payroll_item_id == item.id))
    if payslip is None:
        payslip = Payslip(payroll_item_id=item.id, pdf_path=str(pdf_path))
        db.add(payslip)
    else:
        payslip.pdf_path = str(pdf_path)
        payslip.generated_at = datetime.now(timezone.utc)

    await db.commit()
    await db.refresh(payslip)
    return {
        "success": True,
        "data": {
            "id": payslip.id,
            "payroll_item_id": payslip.payroll_item_id,
            "pdf_path": payslip.pdf_path,
            "generated_at": payslip.generated_at.isoformat(),
        },
        "message": "Payslip generated",
    }


async def generate_employee_payslip(
    payroll_run_id: int,
    employee_id: int,
    db: AsyncSession,
) -> dict:
    """Generate a PDF payslip for one employee inside one payroll run."""
    item = await db.scalar(
        select(PayrollItem).where(
            PayrollItem.payroll_run_id == payroll_run_id,
            PayrollItem.employee_id == employee_id,
        )
    )
    if item is None:
        raise NotFoundError("Payroll item not found for employee")
    return await generate_payslip(item.id, db)


def _write_payslip_pdf(item: PayrollItem, pdf_path: Path) -> None:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas
    except ModuleNotFoundError as exc:
        raise ServiceError("ReportLab is not installed") from exc

    document = canvas.Canvas(str(pdf_path), pagesize=A4)
    width, height = A4
    y = height - 72

    document.setFont("Helvetica-Bold", 16)
    document.drawString(72, y, "Payslip")
    y -= 32

    document.setFont("Helvetica", 10)
    rows = [
        ("Employee", item.employee.name),
        ("Department", item.employee.department),
        ("Position", item.employee.position),
        ("Payroll Period", f"{item.payroll_run.month:02d}/{item.payroll_run.year}"),
        ("Base Salary", str(item.base_salary)),
        ("Overtime Hours", str(item.overtime_hours)),
        ("Overtime Pay", str(item.overtime_pay)),
        ("Late Deduction", str(item.late_deduction)),
        ("Unpaid Leave Deduction", str(item.unpaid_leave_deduction)),
        ("Bonus", str(item.bonus)),
        ("Net Pay", str(item.net_pay)),
        ("Bank Account", item.employee.bank_account or "-"),
    ]

    for label, value in rows:
        document.setFont("Helvetica-Bold", 10)
        document.drawString(72, y, f"{label}:")
        document.setFont("Helvetica", 10)
        document.drawString(220, y, value)
        y -= 22

    document.line(72, y - 4, width - 72, y - 4)
    y -= 28
    document.setFont("Helvetica", 9)
    document.drawString(72, y, "Generated by Payroll Management System")
    document.save()
